---

##################################################
# GLOBAL VARIABLES
##################################################

user: haproxy
passwd: haproxy

##################################################
# DEFAULTS VARIABLES
##################################################

mode: http
stats_user: haproxy
stats_passwd: haproxy
uri_stats: /haproxy_stats

##################################################
# BACKEND VARIABLES
##################################################

balance: roundrobin

##################################################
# FRONTEND VARIABLES
##################################################
