#mysql
bbdd_filename: "BBDD_UAH"
mysql_new_root_pass: "Residente1"

#tomcat
tomcat_archive_name: "apache-tomcat-8.5.16"
tomcat_archive_name_ext: ".tar.gz"
#tomcat_archive_url: "http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.16/bin"
tomcat_archive_url: "http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.16/bin/"
tomcat_home_path: "/opt/tomcat"
tomcat_archive_install_path: "{{tomcat_home_path}}/{{tomcat_archive_name}}"
tomcat_install_link: "{{tomcat_home_path}}/current"
tomcat_roles:
  - manager-gui
  - manager-script
  - manager-jmx
  - manager-status
#tomcat_users: []
tomcat_users:
  - name: tomcat
    password: tomcat
    roles: "manager-gui,manager-script,manager-jmx,manager-status"

tomcat_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre"

# Here are variables related to the Tomcat installation

http_port: 8080
https_port: 8443
ssh_port: 22
application_name: "appuah"

# This will configure a default manager-gui user:

#admin_username: admin
#admin_password: adminsecret
